name: 'Run Checkov with reviewdog'
description: 'A GitHub Action that runs [Checkov](https://www.checkov.io/) for Infrastructure as Code (IaC) security scanning and reports results to pull requests using [reviewdog](https://github.com/reviewdog/reviewdog).'
author: 'Nelson Silva <2473927+fulgas@users.noreply.github.com>'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
    required: true

  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'reviewdog-action-checkov'
    required: true

  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
    required: false

  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review,github-check]'
    default: 'github-pr-check'
    required: false

  filter_mode:
    description: 'Filtering mode for reviewdog [added,diff_context,file,nofilter]'
    default: 'added'
    required: false

  fail_level:
    description: 'If set to none, always use exit code 0. Otherwise fail if findings >= level'
    default: 'error'
    required: false

  working_directory:
    description: 'Directory to run the action from'
    default: '.'
    required: false

  target_dir:
    description: 'Target directory for Checkov to scan'
    default: '.'
    required: false

  skip_check:
    description: 'Space-separated list of Checkov checks to skip (e.g., CKV_AWS_1 CKV_AWS_2)'
    default: ''
    required: false

  framework:
    description: 'Comma-separated list of frameworks to scan (e.g., terraform,kubernetes)'
    default: ''
    required: false

  flags:
    description: 'Additional flags to pass to Checkov'
    default: ''
    required: false

outputs:
  checkov-return-code:
    description: 'Checkov command return code'
    value: ${{ steps.checkov.outputs.checkov-return-code }}

  reviewdog-return-code:
    description: 'reviewdog command return code'
    value: ${{ steps.checkov.outputs.reviewdog-return-code }}

runs:
  using: 'docker'
  image: 'docker://ghcr.io/fulgas/reviewdog-action-checkov:2.3.0'
  env:
    REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
    INPUT_TOOL_NAME: ${{ inputs.tool_name }}
    INPUT_LEVEL: ${{ inputs.level }}
    INPUT_REPORTER: ${{ inputs.reporter }}
    INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
    INPUT_FAIL_LEVEL: ${{ inputs.fail_level }}
    INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
    INPUT_TARGET_DIR: ${{ inputs.target_dir }}
    INPUT_SKIP_CHECK: ${{ inputs.skip_check }}
    INPUT_FRAMEWORK: ${{ inputs.framework }}
    INPUT_FLAGS: ${{ inputs.flags }}

branding:
  icon: 'shield'
  color: 'blue'