name: 'Run Checkov with reviewdog'
description: 'Run Checkov for IaC security scanning and report results using reviewdog'
author: 'Your Name'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true

  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
    required: false

  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review,github-check]'
    default: 'github-pr-check'
    required: false

  filter_mode:
    description: 'Filtering mode for reviewdog [added,diff_context,file,nofilter]'
    default: 'added'
    required: false

  fail_level:
    description: 'If set to none, always use exit code 0. Otherwise fail if findings >= level'
    default: 'error'
    required: false

  working_directory:
    description: 'Directory to run the action from'
    default: '.'
    required: false

  target_dir:
    description: 'Target directory for Checkov to scan'
    default: '.'
    required: false

  skip_check:
    description: 'Space-separated list of Checkov checks to skip (e.g., CKV_AWS_1 CKV_AWS_2)'
    default: ''
    required: false

  framework:
    description: 'Comma-separated list of frameworks to scan (e.g., terraform,kubernetes)'
    default: ''
    required: false

  flags:
    description: 'Additional flags to pass to Checkov'
    default: ''
    required: false

outputs:
  checkov-return-code:
    description: 'Checkov command return code'
    value: ${{ steps.checkov.outputs.checkov-return-code }}

  reviewdog-return-code:
    description: 'reviewdog command return code'
    value: ${{ steps.checkov.outputs.reviewdog-return-code }}


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.filter_mode }}
    - ${{ inputs.fail_level }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.target_dir }}
    - ${{ inputs.skip_check }}
    - ${{ inputs.framework }}
    - ${{ inputs.flags }}

branding:
  icon: 'check-circle'
  color: 'blue'