name: Multi-Framework Security Scan

on:
  pull_request:
    branches: [main]
    paths:
      - '**.tf'
      - '**.yaml'
      - '**.yml'
      - '**.json'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  multi-framework-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan All IaC Frameworks
        uses: fulgas/reviewdog-action-checkov@v2.4.0
        with:
          reporter: github-pr-review
          framework: terraform,kubernetes,cloudformation  # Scan multiple frameworks
          level: warning
          filter_mode: diff_context
          fail_level: error